export const questions = {
    fase: 3,
    numberQuestion: 4,
    totalQuestion: 5,
    descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
    optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
    optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
    optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
    optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
    respostCorrect: 2,
};

export const questionsArray = [
    {
        fase: 1,
        numberQuestion: 1,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },
    {
        fase: 1,
        numberQuestion: 2,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },
    {
        fase: 1,
        numberQuestion: 3,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },
    {
        fase: 2,
        numberQuestion: 1,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },
    {
        fase: 2,
        numberQuestion: 2,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },
    {
        fase: 2,
        numberQuestion: 3,
        totalQuestion: 3,
        descriptionPergunt: 'Qual o grupo em que todas as palavras foram escritas corretamente?',
        optionRespost1: 'Asterístico, beneficiente, meteorologia, entertido',
        optionRespost2: 'Asterisco, beneficente, meteorologia, entretido',
        optionRespost3: 'Asterisco, beneficente, metereologia, entretido',
        optionRespost4: 'Asterístico, beneficiente, metereologia, entretido',
        respostCorrect: 2,
    },

];